"use client";
import "./globals.css";
// import { Inter } from "next/font/google";
import Header from "./component/Header";
import { createContext, useContext, useEffect, useState } from "react";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "../../firebase";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

type Dispatch<T> = (action: T) => void;

// const AuthContext = createContext({
//   user: null,
//   setUser: () => {},
// });

const AuthContext = createContext({
  user: null,
  setUser: () => {},
} as {
  user: null;
  setUser: Dispatch<any>;
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [user, setUser] = useState<any>(null);

  useEffect(() => {
    onAuthStateChanged(auth, (u) => {
      if (u) {
        const uid = u.uid;
        setUser(uid);
        // console.log("🚀 ~ u:", u);
        // // ...
        // console.log("uid", uid);
      } else {
        setUser(null);
        // User is signed out
        // ...
        console.log("user is logged out");
      }
    });
    console.log(auth.currentUser, "auth.currentUser");
  }, []);

  return (
    <>
      <AuthContext.Provider value={{ user, setUser }}>
        <html lang="en">
          <body>
            <Header />
            {children}
          </body>
        </html>
      </AuthContext.Provider>
    </>
  );
}

export const useAuthContext = () => useContext(AuthContext);
